[2025-05-14T13:25:41.766-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-14T13:25:41.777-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_accidents_pipeline.extract_data_postgres scheduled__2025-05-13T00:00:00+00:00 [queued]>
[2025-05-14T13:25:41.784-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_accidents_pipeline.extract_data_postgres scheduled__2025-05-13T00:00:00+00:00 [queued]>
[2025-05-14T13:25:41.784-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-14T13:25:41.805-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_data_postgres> on 2025-05-13 00:00:00+00:00
[2025-05-14T13:25:41.815-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_accidents_pipeline', 'extract_data_postgres', 'scheduled__2025-05-13T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpfh2f7kyh']
[2025-05-14T13:25:41.818-0500] {standard_task_runner.py:105} INFO - Job 22: Subtask extract_data_postgres
[2025-05-14T13:25:41.821-0500] {logging_mixin.py:190} WARNING - /home/jdd/ETL-Global-Road-Accidents/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=60432) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-14T13:25:41.821-0500] {standard_task_runner.py:72} INFO - Started process 60515 to run task
[2025-05-14T13:25:41.874-0500] {task_command.py:467} INFO - Running <TaskInstance: etl_accidents_pipeline.extract_data_postgres scheduled__2025-05-13T00:00:00+00:00 [running]> on host DESKTOP-43HC35D.
[2025-05-14T13:25:41.978-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_accidents_pipeline' AIRFLOW_CTX_TASK_ID='extract_data_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-13T00:00:00+00:00'
[2025-05-14T13:25:41.980-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-14T13:25:42.009-0500] {db_utils.py:50} INFO - ‚úÖ Conexi√≥n a la base de datos 'gra' creada exitosamente.
[2025-05-14T13:25:42.009-0500] {extract.py:26} INFO - Conexi√≥n a la base de datos establecida exitosamente.
[2025-05-14T13:25:45.947-0500] {extract.py:28} INFO - 132000 registros extra√≠dos de la tabla 'accidents'.
[2025-05-14T13:25:45.950-0500] {db_utils.py:64} INFO - üîå Conexi√≥n al engine cerrada correctamente.
[2025-05-14T13:25:45.950-0500] {extract.py:36} INFO - Conexi√≥n cerrada correctamente.
[2025-05-14T13:25:47.697-0500] {etl.py:62} INFO - ‚úÖ Extracci√≥n desde PostgreSQL completada: /tmp/extracted_accidents.csv
[2025-05-14T13:25:47.868-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-05-14T13:25:47.873-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-14T13:25:47.873-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_accidents_pipeline, task_id=extract_data_postgres, run_id=scheduled__2025-05-13T00:00:00+00:00, execution_date=20250513T000000, start_date=20250514T182541, end_date=20250514T182547
[2025-05-14T13:25:47.959-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-14T13:25:47.980-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-14T13:25:47.986-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
