[2025-05-14T11:39:49.916-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-14T11:39:49.932-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.transform_api_data scheduled__2025-05-13T00:00:00+00:00 [queued]>
[2025-05-14T11:39:49.943-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.transform_api_data scheduled__2025-05-13T00:00:00+00:00 [queued]>
[2025-05-14T11:39:49.943-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-14T11:39:49.962-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_api_data> on 2025-05-13 00:00:00+00:00
[2025-05-14T11:39:49.975-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl', 'transform_api_data', 'scheduled__2025-05-13T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmpuh27y121']
[2025-05-14T11:39:49.978-0500] {standard_task_runner.py:105} INFO - Job 13: Subtask transform_api_data
[2025-05-14T11:39:49.979-0500] {logging_mixin.py:190} WARNING - /home/jdd/ETL-Global-Road-Accidents/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=44932) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-14T11:39:49.980-0500] {standard_task_runner.py:72} INFO - Started process 44981 to run task
[2025-05-14T11:39:50.025-0500] {task_command.py:467} INFO - Running <TaskInstance: etl.transform_api_data scheduled__2025-05-13T00:00:00+00:00 [running]> on host DESKTOP-43HC35D.
[2025-05-14T11:39:50.109-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='transform_api_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-13T00:00:00+00:00'
[2025-05-14T11:39:50.110-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-14T11:39:51.274-0500] {logging_mixin.py:190} WARNING - /home/jdd/ETL-Global-Road-Accidents/dags/api.py:91 DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
[2025-05-14T11:39:53.976-0500] {logging_mixin.py:190} WARNING - /home/jdd/ETL-Global-Road-Accidents/source/transform/transform_api.py:122 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-05-14T11:39:55.386-0500] {api.py:95} INFO - ✅ Transformación de datos API completada: /tmp/data/transformed_api_data.csv
[2025-05-14T11:39:55.409-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-05-14T11:39:55.414-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-14T11:39:55.415-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl, task_id=transform_api_data, run_id=scheduled__2025-05-13T00:00:00+00:00, execution_date=20250513T000000, start_date=20250514T163949, end_date=20250514T163955
[2025-05-14T11:39:55.467-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-14T11:39:55.483-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-14T11:39:55.489-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
